# ANP-PROJECT - [EN]

---

# Vinicius Guerra e Ribas -  Energy Sector Analyst
[Energy Engineer (UnB)](https://www.unb.br/) │ [Data Scientist and Analytics (USP)](https://www5.usp.br/)


## [E-mail](mailto:viniciusgribas@gmail.com?Subject=%5BANP-PROJECT%5D%20-%20Contact)│ [Linkedin](https://www.linkedin.com/in/vinicius-guerra-e-ribas/) │[GitHub](https://github.com/viniciusgribas) 

---

# [Project Notebook](https://github.com/viniciusgribas/ANP-PROJECT/blob/main/Codigos_Python/Notebook_Master.ipynb)

---

# ANP PROJECT - [VBA] [PYTHON] - [GitHub](https://github.com/viniciusgribas/ANP-PROJECT)

## PART 1 - INTRODUCTION

The programming languages used were PYTHON and VBA EXCEL.

Seeking to simplify and make clear the flow of activities to obtain the final product, this notebook has been divided into 4 parts.

> PART 1 - INTRODUCTION
 -  Containing a short summary of how the project was developed, the basics and bibliography.

> PART 2 - EXCEL VBA
 - Introducing the `VBA` formulas developed in excel to be called in `python`.

> PART 3 - PYTHON
 - Presenting the `python` code used for this project.

> PART 4 - CONCLUSION
 - Final considerations of the project.

### 1.1 AUXILIARY BIBLIOGRAPHY

 - https://www.automateexcel.com/vba-code-examples/
 - https://www.rondebruin.nl/index.htm
 - https://www.xlwings.org/
 - https://pandas.pydata.org/docs/
 - http://timgolden.me.uk/pywin32-docs/contents.html
 - https://github.com/wesm/pydata-book
 - https://github.com/fzumstein/python-for-excel
 - https://github.com/raizen-analytics/data-engineering-test

### 1.2 PROJECT FLOW

1) At first, the files are only available in excel `".XLS"` format, under the name ["vendas-combustíveis-m3.xls"](https://github.com/viniciusgribas/ANP-PROJECT/tree/main/assets).

2. Within this initial file, there are two pivot tables that are the target. These are:

    - Pivot Table 1 ) "Vendas, pelas distribuidoras, dos derivados combustíveis de petróleo por Unidade da Federação e produto - 2000-2020 (m3)"
    
    - Pivot Table 2 ) "Vendas, pelas distribuidoras, de óleo diesel por tipo e Unidade da Federação - 2013-2020 (m3)"

3) This data, presented by the pivot tables, does not have its data source easily accessible in another spreadsheet. Also, the data is not available through the Excel shortcut: PivotTableTools>Analyze>Change Data Source. This shows the need to extract them using Excel's own `VBA` programming language. The advantage of extracting them this way is not only the reduced time for processes that could be long, but the possibility of applying them via `python`, through the `"wlwings" library`.

- The worksheet, once opened, has by default only one sheet, called "plan1".
- The macros created in VBA are available in the folder [`"\ANP-PROJECT\Codigos_VBA"`](https://github.com/viniciusgribas/ANP-PROJECT/tree/main/Codigos_VBA).
-  To extract this data, 4 macros were created in VBA. These are presented and described in **PART 2 EXCEL**

4) Once all the *VBA - MACROS* have been created, they can be called by `python` and applied there via `xlwings libery`.

5) After applying the Macros on python, the end products of the extraction are two files in `"CSV-UTF8"`:

 - [`PlanConsolidada1.CSV`](https://github.com/viniciusgribas/ANP-PROJECT/tree/main/assets)

 - [`PlanConsolidada2.CSV`](https://github.com/viniciusgribas/ANP-PROJECT/tree/main/assets)

6) These files were managed via the *[Pandas Libery](https://pandas.pydata.org/)* from python. Having the descriptive in **PART 3 PYTHON**

7) Finally, the final product of this project is two files in `"CSV-UTF8"` available in the folder [`"\ANP-PROJECT\Planilhas Finais"`](https://github.com/viniciusgribas/ANP-PROJECT/tree/main/Planilhas%20Finais), according to the following table:

| Column     | Type      |
|------------|-----------|
| year_month | date      |
| uf         | string    |
| product    | string    |
| unit       | string    |
| volume     | double    |
| created_at | timestamp |

 - `Sales_Of_Diesel_By_UF_And_Type.CSV`

 - `Sales_Of_Oil_Derivative_Fuels_By_UF_And_Product.CSV`

## PART 2 - EXCEL VBA


### The first *MACRO* used, created in *VBA - EXCEL*. - [`Desagrupar_TabDinFixa_1()`](https://github.com/viniciusgribas/ANP-PROJECT/blob/main/Codigos_VBA/M%C3%B3dulo1.bas)

Called  `Desagrupar_TabDinFixa_1()`, enables you to drill down on the data in pivot table 1 by performing a cell-by-cell extraction on its columns. Since each column of the pivot table corresponds to a year, an extra worksheet is generated for each year. So, after running this algorithm, the workspace will be left with the initial worksheet plus 21 other worksheets, corresponding to the interval from 2000 to 2020 and totaling 22 worksheets.

---


`Sub Desagrupar_TabDinFixa_1()`

`For Each c In Worksheets("Plan1").Range("C54:W54")`

`    c.Select`

`    Selection.ShowDetail = True`

`    Sheets("Plan1").Select`

`Next c`
    

`End Sub`

*MACRO EXCEL VISUAL BASIC - VBA*

---

### The second *MACRO* used, created in *VBA - EXCEL*. - [`ConsolidacaoDeDados_1()`](https://github.com/viniciusgribas/ANP-PROJECT/blob/main/Codigos_VBA/M%C3%B3dulo2.bas)

Called  `ConsolidacaoDeDados_1()` , it allows you to join all the previously disaggregated spreadsheets into a single one, called `"PlanConsolidada1"`. In addition to grouping them, it also adds a header containing the same headers as the spreadsheets generated by the pivot table. Furthermore, this algorithm deletes all the worksheets that were created, except for the first "Plan1" and exports the consolidated worksheet into an `CSV UTF-8` file called `"PlanConsolidada1.CSV"`.

---
`Sub ConsolidacaoDeDados_1()`

`    Dim sh As Worksheet`
    
`    Dim DestSh As Worksheet`
    
`    Dim Last As Long`
    
`    Dim shLast As Long`
    
`    Dim CopyRng As Range`
    
`    Dim StartRow As Long`
    
`    Dim Plan1 As String`
    
`    Dim PlanConsolidada As String`
    
`    Dim FPath As String`
    
    

`    With Application`

`        .ScreenUpdating = False`

`        .EnableEvents = False`

`    End With`
    
    
`    '#Define the name as "PlanConsolidada1" and the costom path to export in the end of this macro'`
    
`    FPath = "C:\Users\vinic\Documents\GitHub\ANP\ANP-PROJECT\assets\PlanConsolidada1"`
    
  

`    '#Delete the sheet "PlanConsolidada1" if it exist`

`    Application.DisplayAlerts = False`

`    On Error Resume Next`

`    ActiveWorkbook.Worksheets("PlanConsolidada1").Delete`

`    On Error GoTo 0`

`    Application.DisplayAlerts = False`
    
    

`    'Add a worksheet with the name "PlanConsolidada1"`

`    Set DestSh = ActiveWorkbook.Worksheets.Add`

`    DestSh.Name = "PlanConsolidada1"`
     
`    'Add a title in the first row"`
    
`    With Sheets("PlanConsolidada1")`

`    .Range("a1").Value = "COMBUSTÍVEL"`

`    .Range("b1").Value = "ANO"`

`    .Range("c1").Value = "REGIÃO"`

`    .Range("d1").Value = "ESTADO"`

`    .Range("e1").Value = "UNIDADE"`

`    .Range("f1").Value = "JAN"`

`    .Range("g1").Value = "FEV"`

`    .Range("h1").Value = "MAR"`

`    .Range("i1").Value = "ABR"`

`    .Range("j1").Value = "MAI"`

`    .Range("k1").Value = "JUN"`

`    .Range("l1").Value = "JUL"`

`    .Range("m1").Value = "AGO"`

`    .Range("n1").Value = "SET"`

`    .Range("o1").Value = "OUT"`

`    .Range("p1").Value = "NOV"`

`    .Range("q1").Value = "DEZ"`

`    .Range("r1").Value = "TOTAL"`


`End With`
    
    
`    'Fill in the start row (without header)`

`    StartRow = 2`

`    'loop through all worksheets and copy the data to the DestSh`

`    For Each sh In ActiveWorkbook.Worksheets`

`        'Loop through all worksheets except the PlanConsolidada worksheet and the Plan1 worksheet, you can ad more sheets to the array if you want.`

`        If IsError(Application.Match(sh.Name,Array(DestSh.Name, "Plan1"), 0)) Then`

`            'Find the last row with data on the DestSh and sh`
            
`            Last = DestSh.Cells.Find(What:="*", After:=DestSh.Range("A1"), Lookat:=xlPart, LookIn:=xlFormulas,SearchOrder:=xlByRows, SearchDirection:=xlPrevious, MatchCase:=False).Row`

`            shLast = sh.Cells.Find(What:="*", After:=sh.Range("A1"), Lookat:=xlPart, LookIn:=xlFormulas,SearchOrder:=xlByRows, SearchDirection:=xlPrevious, MatchCase:=False).Row`
            

`            'If sh is not empty and if the last row >= StartRow copy the CopyRng`

`            If shLast > 0 And shLast >= StartRow Then`

`                'Set the range that you want to copy `

`                Set CopyRng = sh.Range(sh.Rows(StartRow), sh.Rows(shLast))`

`                'Test if there enough rows in the DestSh to copy all the data`

`                If Last + CopyRng.Rows.Count > DestSh.Rows.Count Then`

`                    MsgBox "There are not enough rows in the Destsh"`

`                    GoTo ExitTheSub`

`                End If`

`                'This copies values/formats`

`                CopyRng.Copy`

`                With DestSh.Cells(Last + 1, "A")`

`                    .PasteSpecial xlPasteValues`

`                    .PasteSpecial xlPasteFormats`

`                    Application.CutCopyMode = False`

`                End With`
`
`           ` End If`
`
`     `   End If`

`    Next`
`
``'Export the new worksheet to a new archive'`


`ThisWorkbook.Sheets("PlanConsolidada1").Copy`

`ActiveWorkbook.SaveAs FPath, FileFormat:=xlCSVUTF8`





`'Delete worksheets after merge data keeping just the Plan1'`

`For Each sh In ThisWorkbook.Worksheets`

`    If sh.Name <> "Plan1" Then`

`       sh.Delete`

`    End If`

`Application.DisplayAlerts = False`

`Next sh`







`'FINAL'`

`ExitTheSub:`

`   'Application.GoTo DestSh.Cells(1)`

`    'AutoFit the column width in the DestSh sheet DestSh.Columns.AutoFit `
`
`    `With Application`

`        .ScreenUpdating = False`

`        .EnableEvents = False`

`    End With`

`End SubM`

*MACRO EXCEL VISUAL BASIC - VBA*

---

### The third *MACRO* used, created in *VBA - EXCEL*. - [`Desagrupar_TabDinFixa_2()`](https://github.com/viniciusgribas/ANP-PROJECT/blob/main/Codigos_VBA/M%C3%B3dulo1.bas)

Being called `Desagrupar_TabDinFixa_2()`, it works analogously to `Desagrupar_TabDinFixa_1()`. However, since this is applied to the second target pivot table, which has a smaller range of years (between 2013 and 2020), its final product corresponds to the initial worksheet plus 8 worksheets, totaling 9 worksheets in the final workbook.

In practice, the only difference to the `Ungroup_TabDinFixa_1()` algorithm is in the argument of the `.Range()` function, which changes according to the pivot table chosen as target.

### The fourth MACRO used, created in *VBA - EXCEL.* - [`ConsolidacaoDeDados_2()`](https://github.com/viniciusgribas/ANP-PROJECT/blob/main/Codigos_VBA/M%C3%B3dulo2.bas)

Being called `ConsolidacaoDeDados_2()`, it works analogously to the first one. Without much change in its code. The changes made to this algorithm, when compared to `ConsolidacaoDeDados_1()`, were basically the names of the exported sheets, which instead of being `"PlanConsolidada1"` became `"PlanConsolidada2"`.

## PART 3 - PYTHON

In [1]:
# Importing all the libraries that will be used
import pandas as pd
import xlwings as xw
import openpyxl as p
import numpy as np
import win32com.client as win32
import os

In [2]:

# Defining the path where the files are and will be saved
patch = "C:\\Users\\vinic\\Documents\\GitHub\\ANP\\ANP-PROJECT\\assets"

# Recognizing the files inside the folder
for dir, sub, files in os.walk(patch):
    for file in files:
        print(os.path.join(dir, file))

# Recognizing the name of the worksheet to work with
wk_name = "vendas-combustiveis-m3.xls"

# Defining the path where the worksheet to be worked on is located
wk_patch = patch + "\\" + wk_name

print("workbook patch: ", wk_patch)

C:\Users\vinic\Documents\GitHub\ANP\ANP-PROJECT\assets\PlanConsolidada1.CSV
C:\Users\vinic\Documents\GitHub\ANP\ANP-PROJECT\assets\PlanConsolidada2.CSV
C:\Users\vinic\Documents\GitHub\ANP\ANP-PROJECT\assets\vendas-combustiveis-m3.xls
workbook patch:  C:\Users\vinic\Documents\GitHub\ANP\ANP-PROJECT\assets\vendas-combustiveis-m3.xls

In [3]:

# Applying the address where the final files will be saved
patch_final = "C:\\Users\\vinic\\Documents\\GitHub\\ANP\\ANP-PROJECT\\Planilhas Finais\\"

# Determining a name for the final files
arquivo_final_1 = 'Sales_Of_Oil_Derivative_Fuels_By_UF_And_Product.csv'

arquivo_final_2 = 'Sales_Of_Diesel_By_UF_And_Type.csv'

In [4]:
# Shortcut to open excel application via win32
excel = win32.gencache.EnsureDispatch('Excel.Application')

excel.Workbooks.Open(wk_patch)

# Assigning active workbook to python via xlwings library. The excel application needs to be open to work.
wk = xw.books.open(wk_patch)

# Calling macros that already exist in excel and assigning them to new variables in python, via xlwings.

    # Macro created to disaggregate the data from the dynamic table 1 ("Sales of petroleum products by Federal Government and products")
desagrupar_TabDinFixa_1 = wk.app.macro("Desagrupar_TabDinFixa_1") 

    # Macro created to disaggregate the data from pivot table 2 ("Diesel sales by Federal Government and container")
desagrupar_TabDinFixa_2 = wk.app.macro("Desagrupar_TabDinFixa_2") 
    
    # Macro created to join the disaggregated data from pivot table 1 into a single DataFrame exported in CSV UTF 8, named "PlanConsolidated1"
consolidacaoDeDados_1 = wk.app.macro("ConsolidacaoDeDados_1") 

    # Macro created to join the disaggregated data from pivot table 2 into a single DataFrame exported in CSV UTF 8, named "PlanConsolidated2"
consolidacaoDeDados_2 = wk.app.macro("ConsolidacaoDeDados_2") 

# Close the excel application, to prevent bugs
excel.Application.Quit()

In [5]:
# Function created to apply the generation flow of DataFrame 1, containing the data of "Petroleum products sales by UF and products" in CSV.
def gerar_df_1():

    excel.Workbooks.Open(wk_patch)
    desagrupar_TabDinFixa_1()
    consolidacaoDeDados_1()
    excel.Application.Quit()
    
# Function created to apply the generation flow of the DataFrame 2, containing the data of "Diesel oil sales by UF and container" in CSV.
def gerar_df_2():
    excel.Workbooks.Open(wk_patch)
    desagrupar_TabDinFixa_2()
    consolidacaoDeDados_2()
    excel.Application.Quit()

In [6]:
# Execution flow for creating the DataFrames to be used

# 1 - Recognize the macros that are in VBA in python

# 2 - Generate the DF 1 - Petroleum products sales by UF and products
gerar_df_1()

# 3 - Generate the DF 2 - Diesel oil sales by UF and container
gerar_df_2()

PARTE 3 - Importando os arquivos criados e os colocando no formato:
 - Column │ Type

    - year_month │ date

   - uf │ string

   - product │ string

   - unit │ string

   - volume │ double
 
   - created_at │ timestamp

In [7]:
# Referencing the file name generated by the above flow. A process analogous to the one for the workbooks already done
df1_name = "PlanConsolidada1.CSV"
df2_name = "PlanConsolidada2.CSV"
df1_path = wk_patch = patch + "\\" + df1_name
df2_path = wk_patch = patch + "\\" + df2_name

df1 = pd.read_csv(df1_path)
df2 = pd.read_csv(df2_path)

# A simple function, to generate a line in print
def linha(x):
    print('\n')
    print('='*x)
    print('\n')

In [8]:
# the ".copy()" command preserves the structure of the original database

petroleo_df = df1.copy()
diesel_df = df2.copy()

In [9]:
# Checking for null values

print("DATA FRAME 1")

print(petroleo_df.isna().sum())

linha(30)

print("DATA FRAME 2")

print(diesel_df.isna().sum())

DATA FRAME 1
COMBUSTÍVEL      0
ANO              0
REGIÃO           0
ESTADO           0
UNIDADE          0
JAN              0
FEV              0
MAR              0
ABR              0
MAI              0
JUN              0
JUL              0
AGO              0
SET              0
OUT            216
NOV            216
DEZ            216
TOTAL            0
dtype: int64


==============================


DATA FRAME 2
COMBUSTÍVEL      0
ANO              0
REGIÃO           0
ESTADO           0
UNIDADE          0
JAN              0
FEV              0
MAR              0
ABR              0
MAI              0
JUN              0
JUL              0
AGO              0
SET              0
OUT            135
NOV            135
DEZ            135
TOTAL            0
dtype: int64

In [10]:
# Substituting NAN values for 0
petroleo_df = petroleo_df.fillna(0)
diesel_df = diesel_df.fillna(0)


# Checking if the values have been replaced
print("DATA FRAME 1")

print(petroleo_df.isna().sum())
linha(30)
print("DATA FRAME 2")

print(diesel_df.isna().sum())

DATA FRAME 1
COMBUSTÍVEL    0
ANO            0
REGIÃO         0
ESTADO         0
UNIDADE        0
JAN            0
FEV            0
MAR            0
ABR            0
MAI            0
JUN            0
JUL            0
AGO            0
SET            0
OUT            0
NOV            0
DEZ            0
TOTAL          0
dtype: int64


==============================


DATA FRAME 2
COMBUSTÍVEL    0
ANO            0
REGIÃO         0
ESTADO         0
UNIDADE        0
JAN            0
FEV            0
MAR            0
ABR            0
MAI            0
JUN            0
JUL            0
AGO            0
SET            0
OUT            0
NOV            0
DEZ            0
TOTAL          0
dtype: int64

In [11]:
# taking a look at the dataframe
petroleo_df.head()

,COMBUSTÍVEL,ANO,REGIÃO,ESTADO,UNIDADE,JAN,FEV,MAR,ABR,MAI,JUN,JUL,AGO,SET,OUT,NOV,DEZ,TOTAL
0,GASOLINA C (m3),2000,REGIÃO NORTE,RONDÔNIA,m3,9563.263,11341.229,9369.746,10719.983,11165.968,12312.451,11220.970,12482.281,13591.122,11940.570,11547.576,10818.094,136073.253
1,GASOLINA C (m3),2000,REGIÃO NORTE,ACRE,m3,3065.758,3495.290,2946.930,3023.920,3206.930,3612.580,3264.460,3835.740,3676.571,3225.610,3289.718,3358.346,40001.853
2,GASOLINA C (m3),2000,REGIÃO NORTE,AMAZONAS,m3,17615.604,20258.200,18741.344,19604.023,20221.674,20792.616,19912.898,21869.338,21145.643,20633.175,20766.918,21180.919,242742.352
3,GASOLINA C (m3),2000,REGIÃO NORTE,RORAIMA,m3,3259.300,3636.216,3631.569,3348.416,3394.016,4078.616,3346.616,4029.900,4358.516,3716.032,3200.400,3339.332,43338.929
4,GASOLINA C (m3),2000,REGIÃO NORTE,PARÁ,m3,28830.479,32297.047,27310.979,29396.384,26511.009,36553.250,31807.840,31009.972,29755.907,28661.951,28145.784,29294.796,359575.398

In [12]:
diesel_df.head()

,COMBUSTÍVEL,ANO,REGIÃO,ESTADO,UNIDADE,JAN,FEV,MAR,ABR,MAI,JUN,JUL,AGO,SET,OUT,NOV,DEZ,TOTAL
0,ÓLEO DIESEL S-10 (m3),2013,REGIÃO NORTE,RONDÔNIA,m3,3517.600,3681.7,4700.67,5339.20,6166.40,6539.65,7283.700,8082.850,7902.55,9383.15,9767.400,9088.800,81453.670
1,ÓLEO DIESEL S-10 (m3),2013,REGIÃO NORTE,ACRE,m3,363.000,410.0,536.00,607.00,740.00,756.00,971.000,1174.000,1240.00,1439.00,1483.000,1483.000,11202.000
2,ÓLEO DIESEL S-10 (m3),2013,REGIÃO NORTE,AMAZONAS,m3,3190.585,3305.0,3391.00,3637.00,4250.00,4576.00,5756.879,6228.636,6334.00,7154.20,6836.300,6784.232,61443.832
3,ÓLEO DIESEL S-10 (m3),2013,REGIÃO NORTE,RORAIMA,m3,795.400,757.2,939.80,1040.60,966.00,992.90,1027.000,1083.800,1311.20,1475.30,1502.700,1531.800,13423.700
4,ÓLEO DIESEL S-10 (m3),2013,REGIÃO NORTE,PARÁ,m3,30137.800,28146.3,31280.50,33033.05,33519.88,34321.53,37168.160,41248.336,40913.48,45383.50,44013.219,41975.030,441140.785

In [ ]:
# Converting the sum of the month column values and the sum of the total column values into a list
petroleo_totals_lista = list(petroleo_df.iloc[0:,5:24].sum())


petroleo_total = 0

linha(30)
print("DATA FRAME 1")

# A test to see if the values of all months summed together, correspond to the totals
for i in range(12):
    petroleo_total = petroleo_totals_lista[i] + petroleo_total
print(" The sum of the values gives us:", petroleo_total)
print(" The sum of the totals gives us: ", petroleo_totals_lista[12])

diferenca_petroleo_total_e_valores = petroleo_total - petroleo_totals_lista[12]

print(" The difference between both is: ", diferenca_petroleo_total_e_valores)

# Here the same logic is applied as above 

diesel_totals_lista = list(diesel_df.iloc[0:,5:18].sum())
diesel_total = 0
linha(30)
print('DATA FRAME 2')

for i in range(12):
    diesel_total = diesel_totals_lista[i] + diesel_total

print(" The sum of the values gives us:", diesel_total)
print(" The sum of the totals gives us: ", diesel_totals_lista[12])

diferenca_diesel_total_e_valores = diesel_total - diesel_totals_lista[12]


print(" The difference between both is: ", diferenca_diesel_total_e_valores)

In [ ]:
# Relocating the column "ANO"
cols1 = petroleo_df.columns.tolist()
cols1 = ['COMBUSTÍVEL',
 'REGIÃO',
 'ESTADO',
 'UNIDADE',
 'ANO',
 'JAN',
 'FEV',
 'MAR',
 'ABR',
 'MAI',
 'JUN',
 'JUL',
 'AGO',
 'SET',
 'OUT',
 'NOV',
 'DEZ',
 'TOTAL']

petroleo_df = petroleo_df[cols1]

petroleo_df.head(5)

# This exploratory analysis reproduces the same pivot table as it was in excel

tab_din_1 = petroleo_df.groupby("ANO").sum()
tab_din_1 = tab_din_1.T

round(tab_din_1,0)

In [ ]:
total_dif1 = 0

# Checking: 1) the observed differences by year; 2) the sum of all differences.

print("DATA FRAME 1")
print("\n")
for i in range(21):
    diferenca1 = (tab_din_1.iloc[0:12,i].sum() - tab_din_1.iloc[12,i].sum())
    total_dif1 = total_dif1 + diferenca1
    print("Difference verified for the year ending in",i, " = ",diferenca1)

linha(30)
diferenca1 = (tab_din_1.iloc[0:12,20].sum() - tab_din_1.iloc[12,20].sum())
print("THE MAIN DIFFERENCE WAS IN 2020 = " , diferenca1)
print("THE TOTAL DIFFERENCE WAS = " , total_dif1)

# It follows from these analyses that the difference is very low. It is however saved.

In [ ]:
# The same analyses performed for Data Frame 1 are repeated for Data Frame 2

diesel_df = diesel_df[cols1]
diesel_df.head(5)

tab_din_2 = diesel_df.groupby("ANO").sum()
tab_din_2 = tab_din_2.T

round(tab_din_2,0)

In [ ]:
# The same analyses performed for Data Frame 1 are repeated for Data Frame 2

total_dif2 = 0

print("DATA FRAME 2")
print("\n")

for i in range(8):
    diferenca2 = (tab_din_2.iloc[0:12,i].sum() - tab_din_2.iloc[12,i].sum())
    total_dif2 = total_dif2 + diferenca2
    print("Difference verified for the year ending in",i+13, " = ",diferenca2)

linha(30)

diferenca2 = (tab_din_2.iloc[0:12,4].sum() - tab_din_2.iloc[12,4].sum())

print("THE MAIN DIFFERENCE WAS IN 2017 = " , diferenca2)
print("THE TOTAL DIFFERENCE WAS = " , total_dif2)

# It follows from these analyses that the difference is very low. It is however saved.

In [ ]:
# Renaming the columns

petroleo_df.columns = ['COMBUSTÍVEL',
 'REGIÃO',
 'ESTADO',
 'UNIDADE',
 'ANO',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 'TOTAL']

petroleo_df.head(5)

In [ ]:
# Renaming the columns

diesel_df.columns = ['COMBUSTÍVEL',
 'REGIÃO',
 'ESTADO',
 'UNIDADE',
 'ANO',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 'TOTAL']

diesel_df.head(5)

In [ ]:
# Joining the values referring to the year column and the columns referring to the months (1 to 12)_ 
# This is accomplished by the "".melt()"" function.

temp1 = petroleo_df.melt(id_vars=["COMBUSTÍVEL","ESTADO","UNIDADE", "ANO"], 
                        value_vars=['1','2','3','4','5','6','7','8','9','10','11','12'])

temp1['year_month'] = temp1[['ANO','variable']].astype(str).agg('-'.join,1)


temp2 = diesel_df.melt(id_vars=["COMBUSTÍVEL","ESTADO","UNIDADE", "ANO"], 
                        value_vars=['1','2','3','4','5','6','7','8','9','10','11','12'])

temp2['year_month'] = temp2[['ANO','variable']].astype(str).agg('-'.join,1)

In [ ]:
# Checking that the difference at the end of this analysis is the same as the difference that has already been saved.

diferenca3 = round(temp1['value'].sum(),2) - round(petroleo_total,2)

print("DataFrame 1 difference: ", diferenca3)

linha(30)

diferenca4 = round(temp2['value'].sum(),2) - round(diesel_total,2)

print("DataFrame 2 difference: ", diferenca4)

In [ ]:
# Viewing the data as it is so far. Preserving what has already been done in the temporary variable "temp".

petroleo_df_final = temp1.copy()

print(petroleo_df_final.head())

linha(30)

diesel_df_final = temp2.copy()

print(diesel_df_final.head())

In [ ]:
# Excluding columns "ANO" anda "variable"
 
petroleo_df_final = petroleo_df_final.drop(columns=["ANO", "variable"])

print(petroleo_df_final.head())

linha(30)

diesel_df_final = diesel_df_final.drop(columns=["ANO", "variable"])

print(diesel_df_final.head())

In [ ]:
# Renaming the columns

cols2 = ['year_month', 'ESTADO', 'COMBUSTÍVEL', 'UNIDADE','value']

petroleo_df_final = petroleo_df_final[cols2]
diesel_df_final = diesel_df_final[cols2]

nomes_DF = ('year_month', 'uf', 'product', 'unit','volume')

petroleo_df_final.columns = nomes_DF
diesel_df_final.columns = nomes_DF


print(petroleo_df_final.head())

linha(30)


print(diesel_df_final.head())

In [ ]:
# Adjusting the "product" column by deleting redundant information.

petroleo_df_final["product"] = petroleo_df_final["product"].str.slice(stop = -4)

print(petroleo_df_final.head())

linha(30)

diesel_df_final["product"] = diesel_df_final["product"].str.slice(stop = -4)
print(diesel_df_final.head())

In [ ]:
# Setting the "year_month" column to Datetime64 format.

petroleo_df_final["year_month"] = pd.to_datetime(petroleo_df_final["year_month"])

print(petroleo_df_final.dtypes)
linha(30)

diesel_df_final["year_month"] = pd.to_datetime(diesel_df_final["year_month"])

print(diesel_df_final.dtypes)

In [ ]:
# Checking the names in the UF column seeking to abbreviate them.

print(petroleo_df_final["uf"].unique())
linha(30)
print(diesel_df_final["uf"].unique())

In [ ]:
# This dictionary being applied with the ".map()" function converts the states into abbreviations

petroleo_df_final["uf"] = petroleo_df_final.uf.map({
'RONDÔNIA':'RO', 'ACRE':'AC', 'AMAZONAS':'AM', 'RORAIMA':'RR', 'PARÁ':'PA', 'AMAPÁ':'AP',
       'TOCANTINS':'TO', 'MARANHÃO':'MA', 'PIAUÍ':'PI', 'CEARÁ':'CE', 'RIO GRANDE DO NORTE':'RN',
       'PARAÍBA':'PB', 'PERNAMBUCO':'PE', 'ALAGOAS':'AL', 'SERGIPE':'SE', 'BAHIA':'BA',
       'MINAS GERAIS':'MG', 'ESPÍRITO SANTO':'ES', 'RIO DE JANEIRO':'RJ', 'SÃO PAULO':'SP',
       'PARANÁ':'PR', 'SANTA CATARINA':'SC', 'RIO GRANDE DO SUL':'RS',
       'MATO GROSSO DO SUL':'MS', 'MATO GROSSO':'MT', 'GOIÁS':'GO', 'DISTRITO FEDERAL':'DF'})



diesel_df_final["uf"] = diesel_df_final.uf.map({
'RONDÔNIA':'RO', 'ACRE':'AC', 'AMAZONAS':'AM', 'RORAIMA':'RR', 'PARÁ':'PA', 'AMAPÁ':'AP',
       'TOCANTINS':'TO', 'MARANHÃO':'MA', 'PIAUÍ':'PI', 'CEARÁ':'CE', 'RIO GRANDE DO NORTE':'RN',
       'PARAÍBA':'PB', 'PERNAMBUCO':'PE', 'ALAGOAS':'AL', 'SERGIPE':'SE', 'BAHIA':'BA',
       'MINAS GERAIS':'MG', 'ESPÍRITO SANTO':'ES', 'RIO DE JANEIRO':'RJ', 'SÃO PAULO':'SP',
       'PARANÁ':'PR', 'SANTA CATARINA':'SC', 'RIO GRANDE DO SUL':'RS',
       'MATO GROSSO DO SUL':'MS', 'MATO GROSSO':'MT', 'GOIÁS':'GO', 'DISTRITO FEDERAL':'DF'})

In [ ]:
# Checking for null values

print("Null in DF1 abbreviations: ", petroleo_df_final["uf"].isnull().sum())

linha(30)

print("Null in DF2 abbreviations: ", diesel_df_final["uf"].isnull().sum())

In [ ]:
print(petroleo_df_final.head())
linha(30)
print(diesel_df_final.head())

In [ ]:
# Converting to the requested formats and creating a new column "created_at", using the function pd.to_datetime('today')

petroleo_df_final['uf'] = petroleo_df_final['uf'].astype(str)
petroleo_df_final['product'] = petroleo_df_final['product'].astype(str)
petroleo_df_final['unit'] = petroleo_df_final['unit'].astype(str)
petroleo_df_final['volume'] = petroleo_df_final['volume'].astype(float)
petroleo_df_final['volume'] =round(petroleo_df_final['volume'] ,2)
petroleo_df_final['created_at'] = pd.to_datetime('today').strftime("%Y-%m-%d")

diesel_df_final['uf'] = diesel_df_final['uf'].astype(str)
diesel_df_final['product'] = diesel_df_final['product'].astype(str)
diesel_df_final['unit'] = diesel_df_final['unit'].astype(str)
diesel_df_final['volume'] = diesel_df_final['volume'].astype(float)
diesel_df_final['volume'] =round(diesel_df_final['volume'] ,2)
diesel_df_final['created_at'] = pd.to_datetime('today').strftime("%Y-%m-%d")



print(petroleo_df_final.head())
linha(30)
print(diesel_df_final.head())

In [ ]:
# Exporting the final files in CSV UTF8 format

petroleo_df_final.to_csv(patch_final+arquivo_final_1, encoding='utf-8', index=False)
diesel_df_final.to_csv(patch_final+arquivo_final_2, encoding='utf-8', index=False)